name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Start up dependencies
        run: docker-compose up -d
      - name: Wait for dependencies to start up
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Master buld tests
        run: |
          go test ./...
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
